import type { Conclusion, InsightContext } from "./types";

// Conclusion engine — the "so what?" layer, now statistically calibrated. It only draws a real
// inference when a test is significant (p < 0.05), tells the user when a pattern is likely noise,
// reports effect sizes (R², η², Cramér's V) and confidence intervals, and ties its own confidence
// label to the p-value. These are AI-generated heuristics, NOT professional advice (see DISCLAIMER).

export const DISCLAIMER =
  "These conclusions are generated by AI using statistical tests (correlation significance, regression, ANOVA, chi-square) on your data. AI and statistics can still mislead — significance isn't proof of cause, and small samples deceive. Treat them as a starting point, not a decision. For anything that matters (financial, medical, legal, or business-critical), consult a qualified professional.";

function pctTxt(x: number): string {
  return `${Math.round(x * 100)}%`;
}
function num(n: number): string {
  if (!Number.isFinite(n)) return "—";
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: Math.abs(n) >= 100 ? 0 : 2 }).format(n);
}
function pTxt(p: number): string {
  if (!Number.isFinite(p)) return "p = n/a";
  return p < 0.001 ? "p < 0.001" : `p = ${p.toFixed(3)}`;
}
function confFromP(p: number): Conclusion["confidence"] {
  return p < 0.01 ? "high" : p < 0.05 ? "medium" : "low";
}

export function deriveConclusions(ctx: InsightContext): Conclusion[] {
  const out: Omit<Conclusion, "id">[] = [];

  // 1. Group differences (ANOVA) — usually the most actionable: a metric varies by a category.
  for (const g of ctx.groupComparisons.filter((g) => g.significant).slice(0, 2)) {
    out.push({
      confidence: confFromP(g.p),
      basis: `ANOVA ${g.metric} by ${g.dimension}`,
      text:
        `${g.metric} differs significantly across ${g.dimension} (ANOVA F = ${num(g.f)}, ${pTxt(g.p)}; ` +
        `${g.dimension} explains ${pctTxt(g.etaSq)} of the variation). "${g.top.name}" is highest (avg ${num(g.top.mean)}) ` +
        `and "${g.bottom.name}" lowest (avg ${num(g.bottom.mean)}). Study what makes "${g.top.name}" different and apply it to the rest.`,
    });
  }

  // 2. Categorical dominance — e.g. "the most common reason for not buying".
  for (const cat of ctx.categories.slice(0, 2)) {
    const top = cat.top[0];
    if (!top) continue;
    const second = cat.top[1];
    if (top.pct >= 0.5) {
      out.push({
        confidence: "high",
        basis: `${cat.column} frequency`,
        text: `"${top.value}" is by far the most common ${cat.column} — ${pctTxt(top.pct)} of cases (${top.count} of ${cat.total}). It dominates, so addressing it would likely move the outcome more than anything else.`,
      });
    } else if (top.pct >= 0.2) {
      const cover = second ? top.pct + second.pct : top.pct;
      out.push({
        confidence: "medium",
        basis: `${cat.column} frequency`,
        text: `The most common ${cat.column} is "${top.value}" (${pctTxt(top.pct)})${second ? `, then "${second.value}" (${pctTxt(second.pct)})` : ""}. The top ${second ? "two" : "one"} cover ${pctTxt(cover)} of cases — concentrate effort there for the biggest effect.`,
      });
    }
  }

  // 3. Correlation as a potential lever — only when statistically significant.
  const sigCorr = ctx.correlations.find((c) => c.significant && c.strength !== "weak");
  if (sigCorr) {
    out.push({
      confidence: confFromP(sigCorr.p),
      basis: `correlation ${sigCorr.a}~${sigCorr.b}`,
      text:
        `${sigCorr.a} and ${sigCorr.b} are significantly correlated (r = ${sigCorr.r.toFixed(2)}, ${pTxt(sigCorr.p)}, ` +
        `95% CI [${sigCorr.ciLow.toFixed(2)}, ${sigCorr.ciHigh.toFixed(2)}], n = ${sigCorr.n}). If ${sigCorr.a} is something you can influence, ` +
        `changing it may shift ${sigCorr.b} in the ${sigCorr.r > 0 ? "same" : "opposite"} direction — but correlation isn't causation, so test a small change first.`,
    });
  } else {
    const noisy = ctx.correlations.find((c) => !c.significant && Math.abs(c.r) > 0.25);
    if (noisy) {
      out.push({
        confidence: "low",
        basis: `correlation ${noisy.a}~${noisy.b}`,
        text: `${noisy.a} and ${noisy.b} look related (r = ${noisy.r.toFixed(2)}) but it is NOT statistically significant (${pTxt(noisy.p)}, n = ${noisy.n}) — likely noise. Don't act on this link without more data.`,
      });
    }
  }

  // 4. Regression — the lever with the most leverage, with its effect size and CI.
  if (ctx.regression && ctx.regression.significant) {
    const r = ctx.regression;
    out.push({
      confidence: confFromP(r.slopeP),
      basis: "regression",
      text:
        `Each 1-unit rise in ${r.driver} is associated with a ${r.slope >= 0 ? "+" : ""}${num(r.slope)} change in ${r.target} ` +
        `(95% CI [${num(r.ciLow)}, ${num(r.ciHigh)}], ${pTxt(r.slopeP)}); the model explains ${pctTxt(r.adjR2)} of ${r.target} (adjusted R²). ` +
        `That makes ${r.driver} the most promising lever to focus on.`,
    });
  }

  // 5. Trends — distinguish a real trend from noise.
  const t = ctx.trends.find((t) => t.direction !== "flat");
  if (t) {
    if (t.significant) {
      out.push({
        confidence: confFromP(t.slopeP ?? 0.05),
        basis: `trend ${t.metric}`,
        text:
          t.direction === "up"
            ? `${t.metric} has a statistically significant upward trend (${pTxt(t.slopeP ?? NaN)}, ${pctTxt(Math.abs(t.changePct))} over the period). The growth is real — consider doubling down on what's driving it.`
            : `${t.metric} has a statistically significant downward trend (${pTxt(t.slopeP ?? NaN)}, ${pctTxt(Math.abs(t.changePct))} over the period). The decline is real — investigate the root cause before it compounds.`,
      });
    } else {
      out.push({
        confidence: "low",
        basis: `trend ${t.metric}`,
        text: `${t.metric} moved ${pctTxt(Math.abs(t.changePct))} end-to-end, but the trend is NOT statistically significant (${pTxt(t.slopeP ?? NaN)}) — it may just be noise. Wait for more periods before reading into it.`,
      });
    }
  }

  // 6. Categorical association (chi-square).
  const assoc = ctx.associations.find((a) => a.significant);
  if (assoc) {
    out.push({
      confidence: confFromP(assoc.p),
      basis: `association ${assoc.a}~${assoc.b}`,
      text: `${assoc.a} and ${assoc.b} are not independent — they're significantly associated (χ² test, ${pTxt(assoc.p)}, Cramér's V = ${assoc.cramersV.toFixed(2)}). Knowing one tells you something about the other; segmenting by ${assoc.a} may reveal different ${assoc.b} patterns.`,
    });
  }

  // 7. Forecast — plan for where it's heading.
  if (ctx.forecast && out.length < 6) {
    const f = ctx.forecast;
    out.push({
      confidence: "medium",
      basis: "forecast",
      text: `If the recent trend holds, ${f.metric} heads toward about ${num(f.projected)} (${f.changePct >= 0 ? "+" : ""}${pctTxt(f.changePct)}) over the next ${f.horizon} period${f.horizon === 1 ? "" : "s"}. Plan around that, and revisit as new data arrives.`,
    });
  }

  // 8. Outliers — trust averages only after checking these.
  const o = ctx.outliers[0];
  if (o && o.count > 0 && out.length < 6) {
    out.push({
      confidence: "medium",
      basis: `outliers in ${o.column}`,
      text: `${o.column} has ${o.count} unusual value${o.count === 1 ? "" : "s"} (beyond 3σ) that can distort averages. Confirm whether they're real or data-entry errors before trusting any ${o.column}-based number.`,
    });
  }

  if (out.length === 0) {
    out.push({
      confidence: "low",
      basis: "overview",
      text: "No statistically significant patterns stood out in this dataset. More rows, or a column capturing the outcome you care about, would let clearer conclusions emerge.",
    });
  }

  return out.slice(0, 7).map((c, i) => ({ id: `concl-${i}`, ...c }));
}
