import type { Conclusion, InsightContext } from "./types";

// Conclusion engine — the "so what?" layer. Where insights DESCRIBE the data, conclusions INTERPRET it
// into action-oriented takeaways (what it likely means / what to consider). It reasons over the
// computed facts (KPIs, correlations, regression, trends, forecast, outliers, category frequencies).
//
// These are AI-generated heuristics, NOT professional advice — the UI shows DISCLAIMER prominently.

export const DISCLAIMER =
  "These conclusions are generated by AI from your data's statistics. AI can be wrong or miss context — treat them as a starting point, not a decision. For anything that matters (financial, medical, legal, or business-critical), consult a qualified professional.";

function pct(x: number): string {
  return `${Math.round(x * 100)}%`;
}
function fmt(n: number): string {
  if (!Number.isFinite(n)) return "—";
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: Math.abs(n) >= 100 ? 0 : 2 }).format(n);
}

export function deriveConclusions(ctx: InsightContext): Conclusion[] {
  const out: Omit<Conclusion, "id">[] = [];

  // 1. Categorical dominance — e.g. "the most common reason for not buying is …".
  for (const cat of ctx.categories.slice(0, 2)) {
    const top = cat.top[0];
    if (!top) continue;
    const second = cat.top[1];
    if (top.pct >= 0.5) {
      out.push({
        confidence: "high",
        basis: `${cat.column} frequency`,
        text: `"${top.value}" is by far the most common ${cat.column} — ${pct(top.pct)} of cases (${top.count} of ${cat.total}). It dominates the picture, so addressing it would likely move the outcome more than anything else.`,
      });
    } else if (top.pct >= 0.2) {
      const cover = second ? top.pct + second.pct : top.pct;
      out.push({
        confidence: "medium",
        basis: `${cat.column} frequency`,
        text: `The most common ${cat.column} is "${top.value}" (${pct(top.pct)})${second ? `, then "${second.value}" (${pct(second.pct)})` : ""}. The top ${second ? "two" : "one"} already cover ${pct(cover)} of cases — concentrate effort there for the biggest effect.`,
      });
    }
  }

  // 2. Correlations as potential levers.
  for (const c of ctx.correlations.filter((c) => c.strength !== "weak").slice(0, 2)) {
    out.push({
      confidence: c.strength === "strong" ? "high" : "medium",
      basis: `correlation ${c.a}~${c.b}`,
      text: `${c.a} and ${c.b} move together (r = ${c.r.toFixed(2)}). If ${c.a} is something you can influence, changing it may shift ${c.b} in the ${c.r > 0 ? "same" : "opposite"} direction — but correlation isn't proof of cause, so test a small change before committing.`,
    });
  }

  // 3. Regression — the lever with the most leverage.
  if (ctx.regression && ctx.regression.r2 >= 0.3) {
    out.push({
      confidence: ctx.regression.r2 >= 0.6 ? "high" : "medium",
      basis: "regression",
      text: `About ${pct(ctx.regression.r2)} of ${ctx.regression.target}'s variation tracks with ${ctx.regression.driver}. That makes ${ctx.regression.driver} the most promising lever to focus on if you want to move ${ctx.regression.target}.`,
    });
  }

  // 4. Trends — momentum to ride or arrest.
  const t = ctx.trends.find((t) => t.direction !== "flat");
  if (t) {
    out.push({
      confidence: Math.abs(t.changePct) > 0.1 ? "high" : "medium",
      basis: `trend ${t.metric}`,
      text:
        t.direction === "up"
          ? `${t.metric} is trending up (${pct(Math.abs(t.changePct))} over the period). Consider doubling down on whatever is driving the growth while it lasts.`
          : `${t.metric} is declining (${pct(Math.abs(t.changePct))} over the period). Worth investigating the root cause now, before it compounds.`,
    });
  }

  // 5. Forecast — plan for where it's heading.
  if (ctx.forecast) {
    const f = ctx.forecast;
    out.push({
      confidence: "medium",
      basis: "forecast",
      text: `If the recent trend holds, ${f.metric} heads toward about ${fmt(f.projected)} (${f.changePct >= 0 ? "+" : ""}${pct(f.changePct)}) over the next ${f.horizon} period${f.horizon === 1 ? "" : "s"}. Plan capacity and targets around that — and revisit as new data arrives.`,
    });
  }

  // 6. Outliers — trust your averages only after checking these.
  const o = ctx.outliers[0];
  if (o && o.count > 0) {
    out.push({
      confidence: "medium",
      basis: `outliers in ${o.column}`,
      text: `${o.column} has ${o.count} unusual value${o.count === 1 ? "" : "s"} that can distort averages. Confirm whether they're real or data-entry errors before trusting any ${o.column}-based number.`,
    });
  }

  if (out.length === 0) {
    out.push({
      confidence: "low",
      basis: "overview",
      text: "No strong patterns stood out in this dataset. More rows, or a column capturing the outcome you care about, would let clearer conclusions emerge.",
    });
  }

  return out.slice(0, 6).map((c, i) => ({ id: `concl-${i}`, ...c }));
}
